version: '3'

tasks:
  run:
    cmds:
      - uv run python -m src

  run_debug:
    cmds:
      - uv run python -m src --debug

  test:
    cmds:
      - uv run nox -s tests

  typecheck:
    cmds:
      - uv tool run ty check

  lint:
    cmds:
      - uv tool run ruff check src/ tests/

  format:
    cmds:
      - uv tool run ruff format src/ tests/
